import { Theme } from "../theme.slint";
export component CButton inherits Rectangle {
    in-out property <string> text;
    in-out property <image> icon;
    in-out property <color> hover-color: Theme.button-background;
    in-out property <bool> has-hover-color: false;
    width: 100px; // Asegúrate de darle ancho si lo estás usando fuera de layout
    height: 30px;
    animate background { duration: 200ms; }
    callback onClick();

    // Contenedor visual
    HorizontalLayout {
        spacing: 10px;
        padding: 5px;
        alignment: center;
        if (icon.width > 0):
            Image {
            source: icon;
            width: 20px;
            height: 20px;
            vertical-alignment: center;
            colorize: Theme.button-text;
        }
        if (text != ""):
            Text {
            text: text;
            color: Theme.button-text;
            vertical-alignment: center;
        }
    }

    // TouchArea encima de todo
    TouchArea {
        x: 0px;
        y: 0px;
        width: parent.width;
        height: parent.height;
        clicked => {
            root.onClick();
        }
    }
}
