import { Button } from "std-widgets.slint";
export component CButton inherits Rectangle {
    height: 30px;
    background: touch.has-hover ? #0c0c0c82 : #0C0C0C00;
    animate background { duration: 200ms; }
    in-out property <string> text;
    in-out property <image> icon;
    callback onClick();
    HorizontalLayout {
        spacing: 10px;
        padding: 5px;
        alignment: center;
        Image {
            source: icon;
            width: 20px;
            height: 20px;
            vertical-alignment: center;
            colorize: #FFFFFF;
        }

        Text {
            text: text;
            color: #FFFFFF;
            vertical-alignment: center;
        }
    }

    touch := TouchArea {
        clicked => {
            root.onClick();
        }
    }
}
