import { Theme } from "../theme.slint";
export component CustomInput inherits Rectangle {
    width: 100%;
    height: 30px;
    border-radius: Theme.border-radius;
    border-width: Theme.border-width;
    border-color: Theme.border-color;
    in-out property <string> label: "Default Label";
    TextInput {
        width: 100%;
        height: 100%;
        y: 4px;
        x: 5px;
        padding: 10px;
        font-size: 12pt;
        color: #FFFFFF;
    }

    Rectangle {
        width: parent.width - 4px;
        height: 5px;
        y: parent.height - 45px;
        x: self.width - 500px;
        Text {
            text: label;
            font-size: 12pt;
            color: #ffffff;
        }
    }
}
