import { StandardButton, HorizontalBox } from "std-widgets.slint";
import { Theme } from "../theme.slint";
import { CInput } from "../widgets/CInput.slint";
import { Icons } from "../icons.slint";
import { CButton } from "../widgets/CButton.slint";

export component NewConnectionDialog inherits Dialog {
    always-on-top: true;
    callback close-dialog();
    Rectangle {
        background: Theme.background;
        border-color: Theme.text;
        border-radius: Theme.border-radius;
        border-width: Theme.border-width;
        VerticalLayout {
            padding: Theme.padding;
            HorizontalLayout {
                spacing: Theme.spacing;
                Image {
                    width: 30px;
                    height: 30px;
                    source: Icons.database;
                    colorize: Theme.text;
                    vertical-alignment: center;
                }

                Text {
                    text: "New Database Connection";
                    font-size: 18pt;
                    color: Theme.text;
                    vertical-alignment: center;
                }

                CButton {
                    height: 40px;
                    icon: Icons.close;
                    onClick => {
                        resetFocus();
                        close-dialog();
                    }
                }
            }

            Rectangle {
                width: 100%;
                height: 1px;
                background: Theme.border-color;
            }

            VerticalLayout {
                spacing: Theme.form-spacing;
                Rectangle {
                    height: 5px;
                }

                connection_name := CInput {
                    label: "Connection Name";
                }

                database_type := CInput {
                    placeholder: "[Cambiar por un select dropdown]";
                }

                HorizontalLayout {
                    width: 100%;
                    db_host := CInput {
                        label: "Host";
                        width: 48.5%;
                    }

                    Rectangle {
                        width: 10px; // Spacer
                    }

                    db_port := CInput {
                        label: "Port";
                        width: 48.5%;
                    }
                }

                db_name := CInput {
                    label: "Database Name";
                }

                db_user := CInput {
                    label: "User";
                }

                db_password := CInput {
                    label: "Password";
                }

                // Action buttons
                HorizontalLayout {
                    spacing: Theme.spacing;
                    width: 100%;
                    CButton {
                        height: 40px;
                        width: 50%;
                        icon: Icons.test_connection;
                        background: Theme.gray;
                        text: "Test Connection";
                        hover-color: Theme.green;
                        has-hover-color: true;
                        onClick => {
                            resetFocus();
                            close-dialog();
                        }
                    }

                    CButton {
                        height: 40px;
                        text: "Save";
                        onClick => {
                            resetFocus();
                            close-dialog();
                            debug("Connection Name: ", connection_name.text);
                            debug("Database Type: ", database_type.text);
                            debug("Host: ", db_host.text);
                            debug("Port: ", db_port.text);
                            debug("Database Name: ", db_name.text);
                            debug("User: ", db_user.text);
                            debug("Password: ", db_password.text);
                        }
                    }
                }
            }

            function resetFocus() {
                connection_name.clear_input_focus();
                database_type.clear_input_focus();
                db_host.clear_input_focus();
                db_port.clear_input_focus();
                db_name.clear_input_focus();
                db_user.clear_input_focus();
                db_password.clear_input_focus();
            }
        }
    }
}
