import { StandardButton } from "std-widgets.slint";
import { CustomInput } from "../widgets/CustomInput.slint";
import { Theme } from "../theme.slint";

export component NewConnectionDialog inherits Dialog {
    always-on-top: true;
    callback close-dialog();
    width: 400px;
    height: 300px;
    Rectangle {
        border-color: Theme.text;
        border-radius: Theme.border-radius;
        border-width: Theme.border-width;
        width: 100%;
        height: 100%;
        background: Theme.background;
        VerticalLayout {
            padding: Theme.padding;
            CustomInput {
                label: "Connection Name";
            }

            HorizontalLayout {
                spacing: Theme.spacing;
                StandardButton {
                    height: 40px;
                    kind: ok;
                    clicked => {
                        close-dialog();
                    }
                }

                StandardButton {
                    height: 40px;
                    kind: cancel;
                    clicked => {
                        close-dialog();
                    }
                }
            }
        }
    }
}
