import { CButton } from "../widgets/CButton.slint";
import { Icons } from "../icons.slint";
import { Theme } from "../theme.slint";

struct MenuItem {
    text: string,
    icon: image,
    callback_id: string,
    color: color,
}

struct MenuGroup {
    text: string,
    icon: image,
    callback_id: string,
    children: [MenuItem],
    colored: color,
}

component MenuItem {
    in property <string> text;
    in property <image> icon;
    in property <string> callback_id;
    in property <color> color: Theme.white;
    callback clicked(string);
    ta := TouchArea {
        Rectangle {
            border-radius: 4px;
            background: ta.has-hover ? Theme.light_gray : transparent;
            animate background {
                duration: 200ms;
                easing: ease-in-out;
            }
            HorizontalLayout {
                padding: 8px;
                spacing: 8px;
                alignment: start;
                if icon.width > 0: Image {
                    source: icon;
                    width: 16px;
                    height: 16px;
                    colorize: color;
                }
                Text {
                    color: color;
                    text: text;
                    vertical-alignment: center;
                }
            }
        }

        clicked => {
            root.clicked(callback_id);
        }
    }
}

component MenuGroup {
    in property <string> text;
    in property <image> icon;
    in property <string> callback_id;
    in property <[MenuItem]> children;
    in property <color> colored: Theme.white;
    callback clicked(string);
    ta := TouchArea {
        Rectangle {
            border-radius: 4px;
            background: ta.has-hover ? Theme.light_gray : transparent;
            animate background {
                duration: 200ms;
                easing: ease-in-out;
            }
            HorizontalLayout {
                padding: 8px;
                spacing: 8px;
                alignment: start;
                if icon.width > 0: Image {
                    source: icon;
                    width: 16px;
                    height: 16px;
                    colorize: colored;
                }
                Text {
                    color: colored;
                    text: text;
                    vertical-alignment: center;
                }
            }
        }

        submenu := PopupWindow {
            y: parent.height + 2px;
            width: max(150px, parent.width);
            close-policy: close-on-click;
            Rectangle {
                height: children.length * 32px + 10px;
                width: 100%;
                background: Theme.gray;
                border-radius: 6px;
                drop-shadow-blur: 10px;
                drop-shadow-offset-y: 4px;
                VerticalLayout {
                    alignment: start;
                    padding: 5px;
                    spacing: 2px;
                    for menuItem in children: MenuItem {
                        text: menuItem.text;
                        icon: menuItem.icon;
                        callback_id: menuItem.callback_id;
                        color: menuItem.color;
                        clicked(callback_id) => {
                            root.clicked(callback_id);
                            submenu.close();
                        }
                    }
                }
            }
        }

        clicked => {
            if (children.length > 0) {
                submenu.show();
            } else {
                root.clicked(callback_id);
            }
        }
    }
}

export component MenuBar {
    width: 100%;
    height: 40px;
    in property <[MenuGroup]> items;
    callback clicked(string);
    items: [
        {
            text: "Add Connection",
            icon: Icons.plus_icon,
            callback_id: "add_connection_menu",
            colored: Theme.white,
            children: [
                {
                    text: "PostgreSQL",
                    icon: Icons.postgres,
                    callback_id: "add_postgresql",
                    color: Theme.white
                },
                { text: "MySQL", icon: Icons.mysql, callback_id: "add_mysql", color: Theme.white },
                { text: "SQLite", icon: Icons.sqlite, callback_id: "add_sqlite", color: Theme.white },
            ]
        },
        {
            text: "Execute",
            icon: Icons.execute,
            callback_id: "execute",
            colored: Theme.green,
            children: []
        },
        {
            text: "Refresh",
            icon: Icons.refresh,
            callback_id: "refresh",
            colored: Theme.white,
            children: []
        },
        {
            text: "Settings",
            icon: Icons.settings,
            callback_id: "settings",
            colored: Theme.white,
            children: []
        },
    ];
    Rectangle {
        width: 100%;
        height: 100%;
        background: Theme.background;
        HorizontalLayout {
            alignment: start;
            padding: 4px;
            HorizontalLayout {
                spacing: 8px;
                alignment: start;
                for menuGroup in items: MenuGroup {
                    text: menuGroup.text;
                    icon: menuGroup.icon;
                    colored: menuGroup.colored;
                    callback_id: menuGroup.callback_id;
                    children: menuGroup.children;
                    clicked(callback_id) => {
                        root.clicked(callback_id);
                    }
                }
            }
        }
    }
}
