import { TextEdit, Button } from "std-widgets.slint";
import { CButton } from "../widgets/CButton.slint";
export component QueryEditor {
    // #region Properties
    in-out property <string> query_text;
    property <string> placeholder: "Write your SQL here...";
    // #endregion
    // #region Callbacks
    callback rExecuteQuery();
    // #endregion

    VerticalLayout {
        padding: 10px;
        spacing: 10px;
        TextEdit {
            text: root.query_text;
            placeholder-text: placeholder;
        }
    }
}
