export global Icons {
    out property <image> icon_orbita: @image-url("icons/icon_orbita.svg");
    out property <image> nude_orbita: @image-url("icons/nude_orbita.svg");
    out property <image> plus_icon: @image-url("icons/add.svg");
    out property <image> close: @image-url("icons/close.svg");
    out property <image> test_connection: @image-url("icons/test.svg");
    out property <image> database: @image-url("icons/database.svg");
    out property <image> execute: @image-url("icons/execute.svg");
    out property <image> refresh: @image-url("icons/refresh.svg");
    out property <image> settings: @image-url("icons/settings.svg");
    // Database icons
    out property <image> postgres: @image-url("icons/dbs/postgres.svg");
    out property <image> mysql: @image-url("icons/dbs/mysql.svg");
    out property <image> sqlite: @image-url("icons/dbs/sqlite.svg");
}
