export global Icons {
    out property <image> icon_orbita: @image-url("icons/icon_orbita.svg");
    out property <image> nude_orbita: @image-url("icons/nude_orbita.svg");
    out property <image> plus_icon: @image-url("icons/add.svg");
    out property <image> close: @image-url("icons/close.svg");
    out property <image> test_connection: @image-url("icons/test.svg");
    out property <image> database: @image-url("icons/database.svg");
}
