import { Button, VerticalBox, HorizontalBox } from "std-widgets.slint";
import { NewConnectionDialog } from "widgets/NewConnectionDialog.slint";

export component AppWindow inherits Window {
    title: "Orbita";
    icon: @image-url("icons/icon_orbita.svg");
    preferred-width: 1200px;
    preferred-height: 800px;
    min-width: 800px;
    min-height: 600px;
    property <bool> dialog-visible: false;
    HorizontalLayout {
        width: 100%;
        height: 100%;
        Rectangle {
            width: 200px;
            height: 100%;
            background: #0000001a;
            HorizontalLayout {
                width: 100%;
                height: 100%;
                alignment: end;
                Button {
                    height: 40px;
                    icon: @image-url("icons/add.svg");
                    clicked => {
                        debug("Add new connection clicked");
                        dialog-visible = true;
                    }
                }
            }
        }

        VerticalLayout {
            Rectangle {
                width: 100%;
                height: 40px;
                background: #8b2323;
            }

            Rectangle {
                width: 100%;
                height: 100%;
                background: #23238b;
            }
        }
    }

    NewConnectionDialog {
        visible: dialog-visible;
        close-dialog => {
            dialog-visible = false;
        }
    }
}
