import { Button, VerticalBox, HorizontalBox } from "std-widgets.slint";
import { NewConnectionDialog } from "screens/NewConnectionDialog.slint";
import { CButton } from "widgets/CButton.slint";
import { Icons } from "icons.slint";
import { Theme } from "theme.slint";
import { Shadow } from "widgets/Shadow.slint";

export component AppWindow inherits Window {
    title: "Orbita";
    icon: Icons.icon_orbita;
    preferred-width: 1200px;
    preferred-height: 800px;
    min-width: 800px;
    min-height: 600px;
    background: Theme.background;
    property <bool> dialog-visible: false;
    CButton {
        width: 200px;
        text: "Custom Button";
        icon: Icons.plus_icon;
        onClick => {
            debug("Custom button clicked");
            dialog-visible = true;
        }
    }

    Shadow {
        width: 100%;
        height: 100%;
        visible: dialog-visible;
        NewConnectionDialog {
            visible: dialog-visible;
            close-dialog => {
                dialog-visible = false;
            }
        }
    }
}
