// #region Imports
import { Button, VerticalBox, HorizontalBox, TextEdit } from "std-widgets.slint";
import { NewConnectionDialog } from "partials/NewConnectionDialog.slint";
import { CButton } from "widgets/CButton.slint";
import { Icons } from "icons.slint";
import { Theme } from "theme.slint";
import { Shadow } from "widgets/Shadow.slint";
import { MenuBar } from "partials/MenuBar.slint";
import { DatabaseBrowser } from "partials/DatabaseBrowser.slint";
import { QueryEditor } from "partials/QueryEditor.slint";
import { GState } from "const.slint";
import { HResize } from "widgets/HResize.slint";
// #endregion
export component AppWindow inherits Window {
    // #region Window Properties
    title: "Orbita";
    icon: Icons.icon_orbita;
    background: Theme.background;
    preferred-height: 700px;
    preferred-width: 1200px;
    // #endregion
    // #region Properties
    in-out property <bool> dialog-visible;
    in-out property <string> connection_name;
    in-out property <string> database_type;
    in-out property <string> db_host;
    in-out property <string> db_port;
    in-out property <string> db_name;
    in-out property <string> db_user;
    in-out property <string> db_password;
    // UI
    in-out property <bool> is_db_connected;
    in-out property <bool> is_tested_connection;
    in-out property <string> query_text;
    in-out property <string> query_result;
    in-out property <string> ui_db_name;
    // #endregion
    // #region Callbacks
    callback rTestConnection();
    callback rAddConnection();
    callback rExecuteQuery();
    // #endregion
    is_db_connected <=> GState.is_db_connected;
    dialog-visible <=> GState.dialog_visible;
    query_result <=> GState.query_result;
    is_tested_connection <=> GState.is_tested_connection;
    VerticalLayout {
        MenuBar {
            clicked(callback_id) => {
                if (callback_id == "add_postgresql") {
                    dialog-visible = true;
                } else if (callback_id == "add_mysql") {
                    dialog-visible = true;
                } else if (callback_id == "add_sqlite") {
                    dialog-visible = true;
                } else if (callback_id == "execute") {
                    rExecuteQuery();
                }
            }
        }

        HResize {
            query_text <=> root.query_text;
        }
    }

    Shadow {
        width: 100%;
        height: 100%;
        visible: dialog-visible;
        NewConnectionDialog {
            visible: dialog-visible;
            connection_name <=> root.connection_name;
            database_type <=> root.database_type;
            db_host <=> root.db_host;
            db_port <=> root.db_port;
            db_name <=> root.db_name;
            db_user <=> root.db_user;
            db_password <=> root.db_password;
            testConnection => {
                rTestConnection();
            }
            addConnection => {
                rAddConnection();
            }
            close-dialog => {
                dialog-visible = false;
            }
        }
    }
}
