export global Theme {
    // Color definitions
    out property <color> background: #0C0C0C;
    out property <color> text: #FFFFFF;
    out property <color> button-background: #0C0C0C82;
    out property <color> button-hover-background: #1C1C1C;
    out property <color> button-text: #FFFFFF;
    out property <color> shadow: #0000003d;
    // Border styles
    out property <length> border-radius: 8px;
    out property <length> border-width: 0.5px;
    out property <color> border-color: #FFFFFF;
    // Margin and padding and spacing
    out property <length> margin: 10px;
    out property <length> padding: 10px;
    out property <length> double-padding: 20px;
    out property <length> spacing: 10px;
    out property <length> form-spacing: 20px;
}
